
export const themeOptions = [
  { label: 'Custom (Pick a color)', value: 'custom', base: '#1E90FF' },
  { label: 'Ocean', value: 'ocean', base: '#1E90FF' },
  { label: 'Woodland', value: 'woodland', base: '#228B22' },
  { label: 'City', value: 'city', base: '#696969' },
  { label: 'Desert', value: 'desert', base: '#C19A6B' },
  { label: 'Sunset', value: 'sunset', base: '#FF4500' },
  { label: 'Midnight', value: 'midnight', base: '#191970' },
  { label: 'Forest', value: 'forest', base: '#2E8B57' },
  { label: 'Volcano', value: 'volcano', base: '#D21F3C' },
  { label: 'Canyon', value: 'canyon', base: '#B87333' },
  { label: 'Wine', value: 'wine', base: '#722F37' },
  { label: 'Rose', value: 'rose', base: '#FF007F' },
  { label: 'Snow', value: 'snow', base: '#EEEFF2' },
  { label: 'Lavender', value: 'lavender', base: '#B57EDC' },
  { label: 'Peach', value: 'peach', base: '#FFCBA4' },
  { label: 'Chocolate', value: 'chocolate', base: '#7B3F00' },
  { label: 'Sky', value: 'sky', base: '#87CEEB' },
  { label: 'Mint', value: 'mint', base: '#98FF98' },
  { label: 'Lemon', value: 'lemon', base: '#FFF44F' },
  { label: 'Lime', value: 'lime', base: '#BFFF00' },
  { label: 'Orange', value: 'orange', base: '#FFA500' },
  { label: 'Strawberry', value: 'strawberry', base: '#FF2400' },
];